name: 'Your name here'
description: 'Provide a description here'
author: 'Your name or organization here'
inputs:
  debug:
    required: false
    description: 'wheter output logs to the console'
    default: false
runs:
  using: 'node16'
  main: 'dist/index.js'
